# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/Practica1/multMatrix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/Practica1/multMatrix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Practica1/multMatrix/CMakeFiles /home/ubuntu/Practica1/multMatrix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Practica1/multMatrix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named serverMultMatrix

# Build rule for target.
serverMultMatrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serverMultMatrix
.PHONY : serverMultMatrix

# fast build rule for target.
serverMultMatrix/fast:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/build
.PHONY : serverMultMatrix/fast

#=============================================================================
# Target rules for targets named clientMultMatrix

# Build rule for target.
clientMultMatrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clientMultMatrix
.PHONY : clientMultMatrix

# fast build rule for target.
clientMultMatrix/fast:
	$(MAKE) -f CMakeFiles/clientMultMatrix.dir/build.make CMakeFiles/clientMultMatrix.dir/build
.PHONY : clientMultMatrix/fast

clientMultMatrix.o: clientMultMatrix.cpp.o

.PHONY : clientMultMatrix.o

# target to build an object file
clientMultMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/clientMultMatrix.dir/build.make CMakeFiles/clientMultMatrix.dir/clientMultMatrix.cpp.o
.PHONY : clientMultMatrix.cpp.o

clientMultMatrix.i: clientMultMatrix.cpp.i

.PHONY : clientMultMatrix.i

# target to preprocess a source file
clientMultMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/clientMultMatrix.dir/build.make CMakeFiles/clientMultMatrix.dir/clientMultMatrix.cpp.i
.PHONY : clientMultMatrix.cpp.i

clientMultMatrix.s: clientMultMatrix.cpp.s

.PHONY : clientMultMatrix.s

# target to generate assembly for a file
clientMultMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/clientMultMatrix.dir/build.make CMakeFiles/clientMultMatrix.dir/clientMultMatrix.cpp.s
.PHONY : clientMultMatrix.cpp.s

multmatrix.o: multmatrix.cpp.o

.PHONY : multmatrix.o

# target to build an object file
multmatrix.cpp.o:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/multmatrix.cpp.o
.PHONY : multmatrix.cpp.o

multmatrix.i: multmatrix.cpp.i

.PHONY : multmatrix.i

# target to preprocess a source file
multmatrix.cpp.i:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/multmatrix.cpp.i
.PHONY : multmatrix.cpp.i

multmatrix.s: multmatrix.cpp.s

.PHONY : multmatrix.s

# target to generate assembly for a file
multmatrix.cpp.s:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/multmatrix.cpp.s
.PHONY : multmatrix.cpp.s

serverMultMatrix.o: serverMultMatrix.cpp.o

.PHONY : serverMultMatrix.o

# target to build an object file
serverMultMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/serverMultMatrix.cpp.o
.PHONY : serverMultMatrix.cpp.o

serverMultMatrix.i: serverMultMatrix.cpp.i

.PHONY : serverMultMatrix.i

# target to preprocess a source file
serverMultMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/serverMultMatrix.cpp.i
.PHONY : serverMultMatrix.cpp.i

serverMultMatrix.s: serverMultMatrix.cpp.s

.PHONY : serverMultMatrix.s

# target to generate assembly for a file
serverMultMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/serverMultMatrix.cpp.s
.PHONY : serverMultMatrix.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/utils.cpp.o
	$(MAKE) -f CMakeFiles/clientMultMatrix.dir/build.make CMakeFiles/clientMultMatrix.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/utils.cpp.i
	$(MAKE) -f CMakeFiles/clientMultMatrix.dir/build.make CMakeFiles/clientMultMatrix.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/serverMultMatrix.dir/build.make CMakeFiles/serverMultMatrix.dir/utils.cpp.s
	$(MAKE) -f CMakeFiles/clientMultMatrix.dir/build.make CMakeFiles/clientMultMatrix.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... serverMultMatrix"
	@echo "... rebuild_cache"
	@echo "... clientMultMatrix"
	@echo "... clientMultMatrix.o"
	@echo "... clientMultMatrix.i"
	@echo "... clientMultMatrix.s"
	@echo "... multmatrix.o"
	@echo "... multmatrix.i"
	@echo "... multmatrix.s"
	@echo "... serverMultMatrix.o"
	@echo "... serverMultMatrix.i"
	@echo "... serverMultMatrix.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

