# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/Practica1/fileManager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/Practica1/fileManager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Practica1/fileManager/CMakeFiles /home/ubuntu/Practica1/fileManager/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/Practica1/fileManager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named serverFileManager

# Build rule for target.
serverFileManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serverFileManager
.PHONY : serverFileManager

# fast build rule for target.
serverFileManager/fast:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/build
.PHONY : serverFileManager/fast

#=============================================================================
# Target rules for targets named clientFileManager

# Build rule for target.
clientFileManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clientFileManager
.PHONY : clientFileManager

# fast build rule for target.
clientFileManager/fast:
	$(MAKE) -f CMakeFiles/clientFileManager.dir/build.make CMakeFiles/clientFileManager.dir/build
.PHONY : clientFileManager/fast

clientFileManager.o: clientFileManager.cpp.o

.PHONY : clientFileManager.o

# target to build an object file
clientFileManager.cpp.o:
	$(MAKE) -f CMakeFiles/clientFileManager.dir/build.make CMakeFiles/clientFileManager.dir/clientFileManager.cpp.o
.PHONY : clientFileManager.cpp.o

clientFileManager.i: clientFileManager.cpp.i

.PHONY : clientFileManager.i

# target to preprocess a source file
clientFileManager.cpp.i:
	$(MAKE) -f CMakeFiles/clientFileManager.dir/build.make CMakeFiles/clientFileManager.dir/clientFileManager.cpp.i
.PHONY : clientFileManager.cpp.i

clientFileManager.s: clientFileManager.cpp.s

.PHONY : clientFileManager.s

# target to generate assembly for a file
clientFileManager.cpp.s:
	$(MAKE) -f CMakeFiles/clientFileManager.dir/build.make CMakeFiles/clientFileManager.dir/clientFileManager.cpp.s
.PHONY : clientFileManager.cpp.s

filemanager.o: filemanager.cpp.o

.PHONY : filemanager.o

# target to build an object file
filemanager.cpp.o:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/filemanager.cpp.o
.PHONY : filemanager.cpp.o

filemanager.i: filemanager.cpp.i

.PHONY : filemanager.i

# target to preprocess a source file
filemanager.cpp.i:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/filemanager.cpp.i
.PHONY : filemanager.cpp.i

filemanager.s: filemanager.cpp.s

.PHONY : filemanager.s

# target to generate assembly for a file
filemanager.cpp.s:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/filemanager.cpp.s
.PHONY : filemanager.cpp.s

serverFileManager.o: serverFileManager.cpp.o

.PHONY : serverFileManager.o

# target to build an object file
serverFileManager.cpp.o:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/serverFileManager.cpp.o
.PHONY : serverFileManager.cpp.o

serverFileManager.i: serverFileManager.cpp.i

.PHONY : serverFileManager.i

# target to preprocess a source file
serverFileManager.cpp.i:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/serverFileManager.cpp.i
.PHONY : serverFileManager.cpp.i

serverFileManager.s: serverFileManager.cpp.s

.PHONY : serverFileManager.s

# target to generate assembly for a file
serverFileManager.cpp.s:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/serverFileManager.cpp.s
.PHONY : serverFileManager.cpp.s

utils.o: utils.cpp.o

.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/utils.cpp.o
	$(MAKE) -f CMakeFiles/clientFileManager.dir/build.make CMakeFiles/clientFileManager.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i

.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/utils.cpp.i
	$(MAKE) -f CMakeFiles/clientFileManager.dir/build.make CMakeFiles/clientFileManager.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s

.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/serverFileManager.dir/build.make CMakeFiles/serverFileManager.dir/utils.cpp.s
	$(MAKE) -f CMakeFiles/clientFileManager.dir/build.make CMakeFiles/clientFileManager.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... serverFileManager"
	@echo "... clientFileManager"
	@echo "... clientFileManager.o"
	@echo "... clientFileManager.i"
	@echo "... clientFileManager.s"
	@echo "... filemanager.o"
	@echo "... filemanager.i"
	@echo "... filemanager.s"
	@echo "... serverFileManager.o"
	@echo "... serverFileManager.i"
	@echo "... serverFileManager.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

