apiVersion: v1
kind: Service
metadata:
 name: filemanager-entrypoint
 namespace: default
spec:
 type: NodePort
 selector:
  app: filemanager
 ports:
 - port: 60000
   targetPort: 60000
   nodePort: 31005
 externalTrafficPolicy: Cluster
